export const AUTHORIZE_USER  = 'AUTHORIZE_USER';
export const UNAUTHORIZE_USER = 'UNAUTHORIZE_USER';
export const SET_ORDERS_RECORD = 'SET_ORDERS_RECORD';
export const SET_IP_ADDRESS = 'SET_IP_ADDRESS';
